### ISSUE TITLE
HipChat notifications not showing up as new messages

### ISSUE THREAD

**Issue by TedStathamPSCL** [kanboard/plugin-hipchat#2]
### Actual behaviour

I've integrated Kanboard into HipChat using this plugin, and it is successfully sending notifications from a Kanboard project into a designated room in HipChat. However, the new notifications do not cause the HipChat client the devs are running to show that there is a new message in the room, and so users have to constantly check in the room to see if there are any notifications from Kanboard. They come up much like status updates entered using HipChat's "/me" command. The users are running the latest version of the HipChat client, running on 64-bit Windows 7 Pro, interfaced to the cloud-based version of HipChat hosted by Atlassian.

I've hunted through the interfaces in Kanboard and HipChat and have tried many different combinations of options to try and enable such a "ping", to no avail. I cannot see any options that would make the integration work the way we would find most useful. I know that the HipChat API supports a flag to cause notifications to "ping" the room, so I suspect that Kanboard's use of the API is leaving that flag at its default, which causes it to not ping the HipChat room.

### Expected behaviour

If the user has configured Kanboard to send the notification with a "ping" to HipChat, it should cause the HipChat web client and Windows client (and other clients for other OSes) to report the new message visually and audibly. As such, Kanboard should provide a configuration option in setting up project integrations with HipChat to let users decided whether or not to cause the "ping" in the associated HipChat room. This way, each team can decided whether or not they want the "ping" to happen. This would also require updating the HipChat API call to pass the appropriate flag based on the configuration setting in Kanboard.

### Steps to reproduce

The HipChat plugin for Kanboard is installed and configured as described here:
   https://github.com/kanboard/plugin-hipchat

The following steps are done using 64-bit Windows 7 Pro, fully patched, with the latest HipChat client from Atlassian installed. Our team is hosted on Atlassian's shared cloud-based HipChat environment.

1. Create, change or move a card in a project that is linked to a HipChat room.
2. Observe that the notification shows up in the HipChat room, but it does not show as a new message in the HipChat client. That is, the red "new message" indicator on the system tray icon does not come on, no "new message" sound is made by the HipChat client, the "new message" counter does not show on the HipChat taskbar icon, and the room list in the HipChat client does not increment the unread message counter. For the web browser based client, obviously we don't get the system tray icon or the task bar icon, but the other parts also do not show any evidence of the new message.

### Configuration

- Kanboard HipChat plugin version: 1.0.6

- Kanboard version: 1.0.44
- Database type and version: sqlite 3.7.9
- PHP version: 5.3.10-1ubuntu3.26
- OS: Linux 3.13.0-34-generic
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by fguillot** [comment]
I don't know if you still interested but with the version 1.0.9 of this plugin, the flag `notify` is now set to true (https://www.hipchat.com/docs/apiv2/method/send_room_notification).

**Comment by TedStathamPSCL** [comment]
Excellent! I'll have to pull the latest version of the plugin and give it a whirl.
